Repository a-quadrato/config.nvim, pull requests merged in 2022-10, with the labels that each got.

#8 [BUGFIX] Fixed deprecated filetype configuarion.
  lua/options.lua
  lua/plugins/init.lua
Labels: bug, config

#9 Cleanup and Ansible Fix
  coc-settings.json
  init.lua
  lua/autocmds.lua
  lua/filetypes.lua
  lua/options.lua
  lua/plugins/ansible.lua
  lua/plugins/coc.lua
  lua/plugins/filetype.lua
  lua/plugins/gruvbox.lua
  lua/plugins/init.lua
  lua/plugins/legendary.lua
  lua/plugins/treesitter.lua
Labels: enhancement, config, CoC

#10 [FIX] Fix double syntax highlighting.
  lua/options.lua
Labels: bug, config

#12 🧹
  .gitignore
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted
